[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[chain]
type = "mainnet"

[intersect]
type = "Point"
value = [
    4640780,
    "f8fa3f085cebc2094b4e3df6d46ee184af6ab44935626b21511aab9983750b1b"
]

[enrich]
type = "Sled"
db_path = "./sled"

[reducer]
type = "Deno"
main_module = "./reduce.js"
storage_command_type = "sql"
use_async = false

[storage]
type = "Postgres"
url = "postgresql://postgres:password@localhost:5432/cexplorer"
