[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[chain]
type = "mainnet"

[intersect]
type = "Point"
value = [
    4492900,
    "b51b1605cc27b0be3a1ab07dfcc2ceb0b0da5e8ab5d0cb944c16366edba92e83"
]

[enrich]
type = "Sled"
db_path = "./sled"

[reducer]
type = "Deno"
main_module = "./reduce.js"
storage_command_type = "sql"
use_async = false

[storage]
type = "Postgres"
url = "postgresql://postgres:password@localhost:5432/cexplorer"
