[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[chain]
type = "mainnet"

[intersect]
type = "Point"
value = [
    0,
    "89d9b5a5b8ddc8d7e5a6795e9774d97faf1efea59b2caf7eaf9f8c5b32059df4"
]

[enrich]
type = "Sled"
db_path = "./sled"

[reducer]
type = "Deno"
main_module = "./reduce.js"
storage_command_type = "sql"
use_async = false

[storage]
type = "Postgres"
url = "postgresql://postgres:password@localhost:5432/cexplorer"
